### ISSUE TITLE
Love the theme but...

### ISSUE THREAD

**Issue by vdruts** [lab-do/obsidian-neo#3]
Would be great to be able to have a colorful background highlight for the explorer pane. Hard to see which file you're on.

At least an option in Stylesettings.

**Comment by x0aa7i** [comment]
You can customize the color by adding the following code to your Obsidian CSS snippets.

```css
body {
	--nav-item-background-active: #403960;
}
```
